### ISSUE TITLE
Unrecognized selector sent to instance 0x280bb7f40

### ISSUE THREAD

**Issue by ibnYusrat** [xlmnxp/nativescript-menu#10]
Hi Again,

Sorry for being so annoying! I just updated the app to the latest version. Once again it works just fine on Android, but on iOS the previous error is gone, now I am getting this: 

![Screen Shot 2019-04-26 at 11 18 32](https://user-images.githubusercontent.com/3955226/56787280-72bb7300-6815-11e9-90dc-56da69c93a99.png)

`CONSOLE LOG file:///app/0.js:118:24: Menu.popup is DEFINED.
-[TNSDictionaryAdapter length]: unrecognized selector sent to instance 0x280bb7f40
CONSOLE LOG file:///app/vendor.js:51513:39: Error: -[TNSDictionaryAdapter length]: unrecognized selector sent to instance 0x280bb7f40`

Can we fix this?

Thanks in advance.

**Comment by ibnYusrat** [comment]
The menu works fine if the actions array is an array of strings. It only produces this problem when we supply array of objects as actions.

**Comment by xlmnxp** [comment]
now I work on other project
few hours and I'll fix it

**Comment by xlmnxp** [comment]
fixed :smile:
