### ISSUE TITLE
Adding iOS specific message for the dialog

### ISSUE THREAD

**Issue by ibnYusrat** [xlmnxp/nativescript-menu#11]
Salaam again,

Would it be possible to add `message` for iOS in the menu options interface? In the first screenshot I am using your `nativescript-menu` and in the second one I am using the generic nativescript dialoge dialog. It would be a very nice addition to the plugin if its easily doable.

Thanks, jazakallah khair.

nativescript-menu:
![before](https://user-images.githubusercontent.com/3955226/56845345-b72a2b80-6874-11e9-8ee2-bebf017e9725.png)

nativescript/ui/dialog:
![after](https://user-images.githubusercontent.com/3955226/56845398-7aaaff80-6875-11e9-8522-bf3a4ec6b0ff.png)

**Comment by xlmnxp** [comment]
is possible

**Comment by xlmnxp** [comment]
done :+1:
