### ISSUE TITLE
Menu fails in iOS every 2nd time with vue

### ISSUE THREAD

**Issue by wendt88** [xlmnxp/nativescript-menu#19]
`TypeError: undefined is not an object (evaluating 'this._control.addObserverForKeyPathOptionsContext')` on every 2nd click starting in:
https://github.com/xlmnxp/nativescript-menu/blob/d6241188dd455ccef087f0c06eaad25aa0c29389/src/menu.ios.ts#L65

When it fails in line
https://github.com/NativeScript/NativeScript/blob/cc97a1680009f1bf6dbf97c421f6e8dc535295b5/nativescript-core/ui/core/view-base/view-base.ts#L343
`this._isLoaded` in `view-base` is false and the method continues

### tns info
✔ Component nativescript has 6.3.3 version and is up to date.
✔ Component tns-core-modules has 6.3.2 version and is up to date.
✔ Component tns-android has 6.3.1 version and is up to date.
✔ Component tns-ios has 6.3.0 version and is up to date.
`"nativescript-menu": "^1.1.3"`

### Playground
https://play.nativescript.org/?template=play-vue&id=l6dBek

**Comment by wendt88** [comment]
I found out, that in your demo (without vue) the function `getCurrentPage` returns `undefined`. With `nativescript-vue` `frame.topmost()` returns the correct `Frame` and so the function `applySelectors` continues with the failing line `view.onLoaded()`

**Comment by xlmnxp** [comment]
I will fix it soon

**Comment by wendt88** [comment]
any progress?

**Comment by xlmnxp** [comment]
> any progress?

I was busy with other things but I promise you I will fix it

**Comment by lostation** [comment]
Thanks for the job you've done xlmnxp ...^^ I'm also waiting for your fix cause I must always tap twice on button to open the menu on iOs ... Anyway... Any workaround to add icon in menu entries ?

**Comment by wendt88** [comment]
My workaround: call the function itself inside the `catch`-block... ugly and can cause an infinity-stack, but it works :D

**Comment by xlmnxp** [comment]
fixed :smile: 
` 📦  nativescript-menu@1.1.4 `

**Comment by xlmnxp** [comment]
> Thanks for the job you've done xlmnxp ...^^ I'm also waiting for your fix cause I must always tap twice on button to open the menu on iOs ... Anyway... Any workaround to add icon in menu entries ?

can you open issue for that?

**Comment by lostation** [comment]
Just tried 1.1.4... but it seems worse...now a simple clic makes the app crashes...

CONSOLE LOG file: node_modules/@nativescript/core/trace/trace.js:165:0: Style: Button(615) going to state: normal
NativeScript caught signal 11.
Native Stack:
1   0x1040b23e1 sig_handler(int)
2   0x7fff518c5b5d _sigtramp
3   0x8600000084
4   0x7fff518f9b85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff518fde58 _Unwind_RaiseException
6   0x7fff4f6dfad3 __cxa_rethrow
7   0x7fff50864cb4 objc_exception_rethrow
8   0x7fff23b06eea CFRunLoopRunSpecific
9   0x7fff38346bb0 GSEventRunModal
10  0x7fff47578dd0 UIApplicationMain
11  0x104aa3c1d ffi_call_unix64
12  0x11234c9c0
JS Stack:
UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at ./main.tns.ts(file:///app/bundle.js:17530:19)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob

**Comment by xlmnxp** [comment]
@lostation  Sorry, I forget to compile Typescript to JavaScript
` 📦  nativescript-menu@1.1.5 ` now fixed
can you try?

**Comment by lostation** [comment]
Re, it doesn't crash anymore and it displays something form first push... but I have only the cancel button showing. The entries doesn't appear anymore...

**Comment by lostation** [comment]
I revert to 1.1.3 ... but need twice push to see the overlay... Thanks anyway for your help

**Comment by lostation** [comment]
Oh oh oh ;) you did it dude ! It works pretty well ! THANK YOU

**Comment by xlmnxp** [comment]
> Oh oh oh ;) you did it dude ! It works pretty well ! THANK YOU

good to hear that :smile:
