### ISSUE TITLE
Possibility of assigning IDs to menu items?

### ISSUE THREAD

**Issue by ibnYusrat** [xlmnxp/nativescript-menu#4]
Is there any possible way of assigning Ids to each menu item and then performing an action based on that ID, instead of just the label.. Because in a multilingual app this would be a big pain in the rear and there probably wouldn't be a way to even use this thing sensibly if the app supports more than 10 languages.. 

Is there a solution to this?

**Comment by xlmnxp** [comment]
I'll support it in next release :)

**Comment by ibnYusrat** [comment]
When do you plan to release the next version? Do you think we can pull the beta or something because I am actually using your library right now..

**Comment by xlmnxp** [comment]
@ibnYusrat few hours :smiley:

**Comment by ibnYusrat** [comment]
بارك الله فيكم

😃

**Comment by xlmnxp** [comment]
@ibnYusrat ويبارك فيك :)
Done

**Comment by xlmnxp** [comment]
you should update plugin in your project
```npm install nativescript@latest```

**Comment by ibnYusrat** [comment]
Ok, and is there a link to the API Reference also please?

**Comment by xlmnxp** [comment]
easy to use
```typescript
Menu.popup({
  view: this.page.getViewById("menuBtn"),
  actions: ["Example","NativeScript","Menu"]
}).then(action => {
  if(action.id == 0){
    alert(action.title);
  } else {
    alert("else action");
  }
}).catch(console.log);
```
