### ISSUE TITLE
Is it possible to specify Action ID in the array?

### ISSUE THREAD

**Issue by ibnYusrat** [xlmnxp/nativescript-menu#5]
I'm wondering if its possible to set Action id for each menu item?

**Comment by xlmnxp** [comment]
you mean pass id to action in `actions` option?

**Comment by ibnYusrat** [comment]
Yes, something like this:

    Menu.popup({
      view: this.page.getViewById("menuBtn"),
      actions: [{id:'asdf', label:"Example"}, {id:'id-vertib', label:"NativeScript"}, {id:555, label:"Menu"}]
    })

**Comment by ibnYusrat** [comment]
That would be very useful.

**Comment by xlmnxp** [comment]
@ibnYusrat I think that possible.
I'll try

**Comment by xlmnxp** [comment]
done

**Comment by ibnYusrat** [comment]
Beautiful!
