### ISSUE TITLE
Type '{ id: string; title: string; }' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by ibnYusrat** [xlmnxp/nativescript-menu#6]
I ran `npm install nativescript-menu@latest` 
but still I am getting: 

`error TS2322: Type '{ id: string; title: string; }' is not assignable to type 'string'.`

Which I think is correct because it should be object I think.. instead of string.. (in index.d.ts)? right?

**Comment by xlmnxp** [comment]
I merged your PR: https://github.com/xlmnxp/nativescript-menu/pull/7
few minutes and I'll send new version to NPM

**Comment by ibnYusrat** [comment]
Please wait a little more I am finding more corrections. I will send merge requests when I'm done. Thanks for the great Nativescript plugin :)

**Comment by xlmnxp** [comment]
```📦  nativescript-menu@1.0.7``` now available in npmjs

**Comment by xlmnxp** [comment]
@ibnYusrat thank you
