### ISSUE TITLE
The latest version is failing on iOS

### ISSUE THREAD

**Issue by ibnYusrat** [xlmnxp/nativescript-menu#9]
The latest version of `nativescript-menu` is failing on iOS. Just yesterday the menu was showing fine on both iPad and iPhone but today after I updated it, the menu doesn't show. 

Can you please check.

P.S It works fine on Android. I've tested it extensively.

**Comment by xlmnxp** [comment]
@ibnYusrat can you tell me what error message

**Comment by ibnYusrat** [comment]
Yes when I tap the button that brings up the menu I get this: 

![Screenshot (5)](https://user-images.githubusercontent.com/3955226/56782785-1864e700-6802-11e9-8871-5c38fbf4b2bc.png)

`CONSOLE LOG file:///app/0.js:120:20: Select group for searching called.
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not a function (near '...nativescript_menu__WEBPACK_IMPORTED_MODULE_4__["Menu"].popup...')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 16793745,
"rootNodeFlags": 17,
"nodeMatchedQueries": 6,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": -1,
"flags": 16,
"childFlags": 0,
"directChildFlags": 0,
"childMatchedQueries": 0,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"ngContentIndex": -1,
"childCount": 0,
"bindings": [],
"bindingFlags": 0,
"outputs": [],
"element": null,
"provider": {
"deps": []
},
"text": null,
"query": null,
"ngContent": null
},
{
"nodeIndex": 1,
"parent": null,
"renderParent": null,
"bindingIndex":<\M-b\M^@\M-&>
removing all entries config 0x282c40cc0
TIC TCP Conn Cancel [14:0x28192b0c0]`


And my function looks something like this:
![Screenshot (7)](https://user-images.githubusercontent.com/3955226/56782850-61b53680-6802-11e9-9afd-57eeaf9e2558.png)

i-e:
`selectGroupForSearching() {
        console.log('Select group for searching called.');
        Menu.popup({
            view: this.page.getViewById('menuLabl'),
            actions: [{id: '', title: localize('all_groups_label')}, ...this.companyGroups]
        }).then(value => {
            if (value) {
                this.currentlySelectedSearchGroup = value;
            }
        }).catch(console.log);
    }`

This does work just fine on Android by the way.

**Comment by xlmnxp** [comment]
I'll fix it soon

**Comment by ibnYusrat** [comment]
Thank you very much. This is really strange because if I do something like

`if (Menu.popup){
console.log('Menu.popup is Defined.');
} else {
console.log('Menu.popup is undefined.');
}`

I actually get `Menu.popup is DEFINED` on Android and `Menu.popup is undefined.` on iOS...

Strange.. 🤔

**Comment by xlmnxp** [comment]
I fix it
the error come because I forget define popup as static method in iOS

**Comment by xlmnxp** [comment]
```📦  nativescript-menu@1.0.8``` available now
